### PR TITLE
Adding calendar creation

### PR DESCRIPTION
**Pull request by ChrisThompsonTLDR**

### CODE REVIEW

**Comment by lanlin** [comment]
@ChrisThompsonTLDR sorry late to respond. thanks for your PR. 

I think it's may better to keep the update & delete methods as the Nylas doc REST API includes https://docs.nylas.com/reference#calendars.

And may you have a little more time to add Free / Busy Status methods together, that will make our calendar completed.

**Comment by ChrisThompsonTLDR** [comment]
The Nylas API for calendar update and delete do not actually work.  I have spoken with Nylas engineers about it and they have said that because not all providers (Outlook) support calendar editing, Nylas doesn't support it for any calendars.

**Comment by lanlin** [comment]
@ChrisThompsonTLDR ok, thanks again

**Comment by ChrisThompsonTLDR** [comment]
@lanlin can you create a new release with this PR?

**Comment by lanlin** [comment]
@ChrisThompsonTLDR  https://github.com/lanlin/nylas-php/releases/tag/4.2.2

**Pull request merged**
